[package]
name = "identicon-rs"
version = "1.4.0"
authors = ["Nia Watts <niawatts95@gmail.com>"]
edition = "2018"
readme = "README.md"
description = """
identicon-rs is a library built around custom generation of identicon images.
"""
documentation = "https://docs.rs/identicon-rs"
homepage = "https://github.com/fluffy-samurai/identicon-rs"
repository = "https://github.com/fluffy-samurai/identicon-rs"
license = "MIT"
keywords = ["image", "identicon", "avatar"]
categories = ["graphics", "multimedia::images", "value-formatting", "visualization"]

[dependencies]
image = "0.22.0"
sha2 = "0.8.0"
palette = "0.4.1"

[dev-dependencies]
actix-web = "1.0.0"
